name: Kind Antrea Cyclonus
on:
  workflow_dispatch:
    inputs:
      cyclonus_args:
        description: "args to pass on to Cyclonus"
        required: false
        default: "generate --include conflict --job-timeout-seconds 2 --server-protocol=tcp,udp"
#  schedule:
    # See https://crontab.guru/#0_0_*_*_0:
    #   At 00:00 on Sunday.
#    - cron: '0 0 * * 0'

jobs:
  test-kind-antrea:
    name: Run Cyclonus on KinD/Antrea
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run Cyclonus
        working-directory: hack/kind
        run: CNI=antrea RUN_FROM_SOURCE=true FROM_SOURCE_ARGS="${{ github.event.inputs.cyclonus_args }}" ./run-cyclonus.sh
