name: Kind CNI From Source
on:
  workflow_dispatch:
    inputs:
      cni:
        description: "name of CNI to use"
        required: true
      cyclonus_args:
        description: "args to pass on to Cyclonus"
        required: false
        default: "generate include --conflict --job-timeout-seconds 2"

jobs:
  test-kind-calico:
    name: Run Cyclonus on KinD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run Cyclonus
        working-directory: hack/kind
        run: CNI=${{ github.event.inputs.cni }} RUN_FROM_SOURCE=true FROM_SOURCE_ARGS="${{ github.event.inputs.cyclonus_args }}" ./run-cyclonus.sh
