name: Kind Cilium Cyclonus
on:
  workflow_dispatch:
    inputs:
      cyclonus_args:
        description: "args to pass on to Cyclonus"
        required: false
        default: "generate --include conflict --job-timeout-seconds 2 --server-protocol=tcp,udp --ignore-loopback=true"
#  schedule:
    # At 03:00 on Sunday.
#    - cron: '0 3 * * 0'

jobs:
  test-kind-cilium:
    name: Run Cyclonus on KinD/Cilium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run Cyclonus
        working-directory: hack/kind
        run: CNI=cilium RUN_FROM_SOURCE=true FROM_SOURCE_ARGS="${{ github.event.inputs.cyclonus_args }}" ./run-cyclonus.sh
